#ifndef MOTOR_FAULT_DEFS
#define MOTOR_FAULT_DEFS

typedef enum {
    VCP_UV_FAULT,
    OVP_FAULT,
    OCP_FAULT,
    MTR_LCK_FAULT,
    HW_LOCK_LIMIT_FAULT,
    LOCK_LIMIT,
    IPD_T1_FAULT,
    IPD_T2_FAULT,
    IPD_FREQ_FAULT,
    MPET_IPD_FAULT,
    MPET_BEMF_FAULT,
    VM_OVER_FAULT,
    VM_UNDER_FAULT,
    EXTERNAL_WDG_FAULT,
    CURR_LOOP_SATURATION_FAULT,
    SPEED_LOOP_SATURATION_FAULT,
    THERMAL_FAULT,
    FET_THERMAL_FAULT
} gate_driver_fault_e;

typedef enum {

} controller_fault_e

#define CONTROLLER_FAULT_MASK 0x80000000
#define IPD_FREQ_FAULT_MASK   0x20000000
#define IPD_T1_FAULT_MASK     0x10000000
#define IPD_T2_FAULT_MASK     0x08000000
#define MPET_IPD_FAULT_MASK   0x02000000
#define MPET_BEMF_FAULT_MASK  0x01000000
#define ABN_SPEED_MASK        0x00800000
#define ABN_BEMF_FAULT_MASK   0x

#endif